---
title: "Final Project Proposal"
author: "Quinn Anderson, Laylah Jones, Wynter Henry"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

### Proposal guidelines:

First, define teams and propose project. This proposal should be a half-page to a page in length and include: 

* The group members (names and UNIs)
* The tentative project title
* The motivation for this project
* The intended final products
* The anticipated data sources
* The planned analyses / visualizations / coding challenges
* The planned timeline

This is intended to describe a project that is in the planning stages. Only one team member should submit this proposal via Canvas.

Please also submit (only once per team) a list of your team’s UNIs using this form. Doing so will help us keep track of teams.
trying to comitt
### P8105 Final Project Proposal

Project title: Rat Reign: Unveiling the Truth Behind NYC's Rodent Infestation 

<<<<<<< HEAD
This is a project proposal for the following team members: Wynter Henry (wch2124), Quinn Anderson (UNI qra2000), and Laylah Jones (UNI ). We are proposing to investigate the presence of rats in the city to determine if they really rule the Big Apple. We will utilize data sourced from Transit, NYC Rodent Inspection data, and NYC borough data to investigate where rodent inspection and activity is most prevalent [add data source links]. Our hope is to add further insight into a rat-tastic issue the city faces. 

The intended final products for this project are summary report of our findings as well as a project website. Potential challenges of this project include aligning data sources,... etc.
=======
This is a project proposal for the following team members: Wynter Henry (UNI ), Quinn Anderson (UNI qra2000), and Laylah Jones (UNI lsj2122). We are proposing to investigate the presence of rats in the city to determine if they really rule the big apple. We will utilize data sourced from Transit, NYC Rodent Inspection data, and NYC borough data to investigate where rodent inspection and activity is most prevalent [add data source links]. Our hope is to add further insight into a rat-tastic issue the city faces. 

In conducting our research, some important questions we would like to explore are:

1. What is the overall frequency of rat sightings? 
2. What is the distribution of rat sightings across different boroughs in NYC?
3. Are there any seasonal trends or patterns in rat sightings?
4. Is there any correlation between monthly collection of garbage tonnages that the NYC Department of Sanitation collects and the prevalence of rat sightings?
5. Which borough has the most monthly reported rat sightings?

The intended final products for this project consist of a comprehensive report summarizing our findings, interactive data visualizations, as well as a project website. Our planned analyses/visualizations include a geospatial analysis to map the frequency of rat sightings across the different boroughs, a comparative analysis of rat sightings in relation to garbage collection, and interactive visualizations to illustrate trends and patterns in rat infestation.  Potential challenges of this project include aligning data sources..... etc. 
>>>>>>> 7363e621bfc536d2d1006e922a6d75608a8a99ef

#### *Please see below for our draft project timeline and milestones:*

November 6 - 12

* Data import, cleaning, tidying
* Begin initial data manipulation
* Submit proposal and Github repo (deliverable)

November 12 - 19

* Complete data tidying
* Begin data manipulation
* Begin data exploration
* Project review meeting (assigned)

November 20 - 26

* Data exploration
* Begin website (deliverable) 
* Begin report (deliverable)

November 27 - December 4

* Complete website, screencast, and report (deliverables)

December 4 - December 9

* Submit: 
  * Report
  * Webpage and screencast
  * Peer assessment 

December 13

* In class presentation